name: Contexto
on: [push]
jobs:
  contexto:
    if: ${{ github.ref_name == 'aprendiendo-github-actions' }}
    runs-on: ubuntu-latest
    steps:
      - name: imprimir
        run: echo "nos encontramos en la rama ${{ github.ref_name }}"
    
