name: Hola Mundo Kotlin
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@v1

      - name: Ejecutar Kotlin directamente
        run: |
          kotlinc Main.kt -include-runtime -d Main.jar
          java -jar Main.jar
